
version: "3"

tasks:
  run:
    desc: Show ES gtd index settings
    cmds:
      -  cmd: curl -sk -u "${USERNAME}:${PASSWORD}" "https://localhost:9200/${INDEX_NAME}/_settings" | jq
         silent: true
